version: "3"
services:
  api:
    build:
      context: ./timwispot-api
      args:
        - NODE_JS_VERSION=14.17.6
    volumes:
      - ./timwispot-api:/usr/src/timwispot-api
    environment: 
      - API_PORT=9000
    ports:
      - "9000:9000"

  web:
    build:
      context: ./timwispot-web
      args:
        - "NODE_JS_VERSION=14.17.6"
    volumes:
      - ./timwispot-web:/usr/src/timwispot-web
      # - /usr/src/app/timwispot-web/node_modules
    environment:
      - API_PORT=8001
      - API_HOST=api
    ports:
      - "8088:3000"
    depends_on:
      - api

  # db:
  #   image: mysql:5
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
    